# Generated by Django 5.0 on 2025-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_elday_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elday',
            name='day_of_week',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('tuesday', 'tuesday'), ('Wednesday', 'Wednesday'), ('thursday', 'thursday'), ('Friday', 'Friday')], max_length=50, unique=True),
        ),
    ]
