# Generated by Django 5.0 on 2025-10-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_elday_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elday',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=50, unique=True),
        ),
    ]
