# Generated by Django 5.0 on 2025-10-14 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_elday_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time', 'agent')},
        ),
    ]
