# Generated by Django 5.0 on 2025-10-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('time',)},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
