# Generated by Django 5.0 on 2025-10-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date',)},
        ),
    ]
