# Generated by Django 5.0 on 2025-10-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date', 'time')},
        ),
    ]
