# Generated by Django 5.0 on 2025-10-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
