# Generated by Django 5.0 on 2025-10-16 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reservation_is_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='elday',
            constraint=models.UniqueConstraint(fields=('agent', 'day_of_week', 'start_time', 'end_time'), name='Unique_agent_working_times'),
        ),
    ]
