# Generated by Django 5.0 on 2025-10-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_elday_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_viewed',
        ),
    ]
