# Generated by Django 5.2.7 on 2025-11-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_reservation_is_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date',)},
        ),
    ]
