# Generated by Django 5.0 on 2025-10-14 15:48

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Specialtie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('job_title', models.CharField(max_length=50)),
                ('job_des', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='UserImages/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG')),
                ('about_me', models.TextField()),
                ('my_approach', models.TextField()),
                ('office', models.CharField(max_length=200)),
                ('number_of_reservations', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_duration', models.CharField(choices=[('1 Hour', '1 Hour'), ('2 Hours', '2 Hours'), ('3 Hours', '3 Hours')], max_length=50)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('certifications', models.ManyToManyField(to='accounts.certification')),
                ('graduation', models.ManyToManyField(to='accounts.graduation')),
                ('recent_achievement', models.ManyToManyField(blank=True, to='accounts.recentachievement')),
                ('specialties', models.ManyToManyField(to='accounts.specialtie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
