# Generated by Django 5.0.6 on 2025-09-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='graduation',
        ),
        migrations.AddField(
            model_name='user',
            name='graduation',
            field=models.ManyToManyField(to='accounts.graduation'),
        ),
    ]
