# Generated by Django 5.0 on 2025-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_duration',
            field=models.CharField(choices=[(1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours')], max_length=50),
        ),
    ]
