# Generated by Django 5.0 on 2025-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_duration',
            field=models.CharField(choices=[('1 Hour', 1), ('2 Hours', 2), ('3 Hours', 3)], max_length=50),
        ),
    ]
