# Generated by Django 5.0 on 2025-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_duration',
            field=models.IntegerField(choices=[(1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours')]),
        ),
    ]
