# Generated by Django 5.0 on 2025-10-15 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appointments',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
