# Generated by Django 5.0 on 2025-10-15 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
