# Generated by Django 5.0 on 2025-10-16 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointments',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
