# Generated by Django 5.0 on 2025-10-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recent_achievement',
            new_name='recent_achievements',
        ),
    ]
