# Generated by Django 5.0 on 2025-10-17 10:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_recent_achievement_user_recent_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserImages/'),
        ),
        migrations.AddField(
            model_name='graduation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserImages/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='accounts.certification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation',
            field=models.ManyToManyField(blank=True, to='accounts.graduation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='UserImages/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_des',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_approach',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='EG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='accounts.specialtie'),
        ),
    ]
