# Generated by Django 5.0 on 2025-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_certification_image_graduation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_duration',
            field=models.IntegerField(choices=[(0.5, '1/2 Hour'), (1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours')]),
        ),
    ]
