# Generated by Django 5.0 on 2025-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_duration',
            field=models.IntegerField(choices=[(1, '1/2 Hour'), (2, '1 Hour'), (3, '2 Hours'), (4, '3 Hours')]),
        ),
    ]
