# Generated by Django 5.2.7 on 2026-02-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_duration',
            field=models.IntegerField(choices=[(1, '1/2 Hour'), (2, '1 Hour'), (3, '2 Hours'), (4, '3 Hours')], null=True),
        ),
    ]
